// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module PTW(
  input         clock,
                io_requestor_0_req_bits_bits_need_gpa,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_0_req_bits_bits_stage2,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_status_debug,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_0_pmp_0_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_0_pmp_0_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_0_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_0_pmp_0_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_0_pmp_0_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_0_pmp_0_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_1_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_0_pmp_1_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_1_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_0_pmp_1_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_0_pmp_1_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_0_pmp_1_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_2_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_0_pmp_2_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_2_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_0_pmp_2_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_0_pmp_2_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_0_pmp_2_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_3_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_0_pmp_3_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_3_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_0_pmp_3_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_0_pmp_3_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_0_pmp_3_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_4_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_0_pmp_4_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_4_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_0_pmp_4_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_0_pmp_4_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_0_pmp_4_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_5_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_0_pmp_5_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_5_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_0_pmp_5_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_0_pmp_5_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_0_pmp_5_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_6_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_0_pmp_6_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_6_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_0_pmp_6_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_0_pmp_6_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_0_pmp_6_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_7_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_0_pmp_7_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_0_pmp_7_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_0_pmp_7_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_0_pmp_7_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_0_pmp_7_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_requestor_1_req_bits_bits_need_gpa,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_1_req_bits_bits_stage2,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_status_debug,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_requestor_1_pmp_0_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_1_pmp_0_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_0_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_1_pmp_0_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_1_pmp_0_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_1_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_1_pmp_1_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_1_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_1_pmp_1_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_1_pmp_1_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_2_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_1_pmp_2_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_2_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_1_pmp_2_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_1_pmp_2_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_3_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_1_pmp_3_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_3_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_1_pmp_3_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_1_pmp_3_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_4_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_1_pmp_4_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_4_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_1_pmp_4_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_1_pmp_4_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_5_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_1_pmp_5_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_5_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_1_pmp_5_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_1_pmp_5_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_6_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_1_pmp_6_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_6_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_1_pmp_6_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_1_pmp_6_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_7_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [1:0]  io_requestor_1_pmp_7_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output        io_requestor_1_pmp_7_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [26:0] io_requestor_1_pmp_7_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [28:0] io_requestor_1_pmp_7_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  output [63:0] io_requestor_1_customCSRs_csrs_0_value,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_status_debug,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_0_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [1:0]  io_dpath_pmp_0_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_0_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_0_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_0_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [26:0] io_dpath_pmp_0_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [28:0] io_dpath_pmp_0_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_1_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [1:0]  io_dpath_pmp_1_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_1_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_1_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_1_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [26:0] io_dpath_pmp_1_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [28:0] io_dpath_pmp_1_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_2_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [1:0]  io_dpath_pmp_2_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_2_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_2_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_2_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [26:0] io_dpath_pmp_2_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [28:0] io_dpath_pmp_2_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_3_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [1:0]  io_dpath_pmp_3_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_3_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_3_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_3_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [26:0] io_dpath_pmp_3_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [28:0] io_dpath_pmp_3_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_4_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [1:0]  io_dpath_pmp_4_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_4_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_4_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_4_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [26:0] io_dpath_pmp_4_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [28:0] io_dpath_pmp_4_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_5_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [1:0]  io_dpath_pmp_5_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_5_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_5_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_5_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [26:0] io_dpath_pmp_5_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [28:0] io_dpath_pmp_5_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_6_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [1:0]  io_dpath_pmp_6_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_6_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_6_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_6_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [26:0] io_dpath_pmp_6_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [28:0] io_dpath_pmp_6_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_7_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [1:0]  io_dpath_pmp_7_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input         io_dpath_pmp_7_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_7_cfg_w,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
                io_dpath_pmp_7_cfg_r,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [26:0] io_dpath_pmp_7_addr,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [28:0] io_dpath_pmp_7_mask,	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
  input  [63:0] io_dpath_customCSRs_csrs_0_value	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:220:14]
);

  Arbiter arb (	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:236:19]
    .io_in_0_bits_bits_need_gpa (io_requestor_0_req_bits_bits_need_gpa),
    .io_in_0_bits_bits_stage2   (io_requestor_0_req_bits_bits_stage2),
    .io_in_1_bits_bits_need_gpa (io_requestor_1_req_bits_bits_need_gpa),
    .io_in_1_bits_bits_stage2   (io_requestor_1_req_bits_bits_stage2),
    .io_out_bits_bits_need_gpa  (/* unused */),
    .io_out_bits_bits_stage2    (/* unused */)
  );
  assign io_requestor_0_status_debug = io_dpath_status_debug;
  assign io_requestor_0_pmp_0_cfg_l = io_dpath_pmp_0_cfg_l;
  assign io_requestor_0_pmp_0_cfg_a = io_dpath_pmp_0_cfg_a;
  assign io_requestor_0_pmp_0_cfg_w = io_dpath_pmp_0_cfg_w;
  assign io_requestor_0_pmp_0_cfg_r = io_dpath_pmp_0_cfg_r;
  assign io_requestor_0_pmp_0_addr = io_dpath_pmp_0_addr;
  assign io_requestor_0_pmp_0_mask = io_dpath_pmp_0_mask;
  assign io_requestor_0_pmp_1_cfg_l = io_dpath_pmp_1_cfg_l;
  assign io_requestor_0_pmp_1_cfg_a = io_dpath_pmp_1_cfg_a;
  assign io_requestor_0_pmp_1_cfg_w = io_dpath_pmp_1_cfg_w;
  assign io_requestor_0_pmp_1_cfg_r = io_dpath_pmp_1_cfg_r;
  assign io_requestor_0_pmp_1_addr = io_dpath_pmp_1_addr;
  assign io_requestor_0_pmp_1_mask = io_dpath_pmp_1_mask;
  assign io_requestor_0_pmp_2_cfg_l = io_dpath_pmp_2_cfg_l;
  assign io_requestor_0_pmp_2_cfg_a = io_dpath_pmp_2_cfg_a;
  assign io_requestor_0_pmp_2_cfg_w = io_dpath_pmp_2_cfg_w;
  assign io_requestor_0_pmp_2_cfg_r = io_dpath_pmp_2_cfg_r;
  assign io_requestor_0_pmp_2_addr = io_dpath_pmp_2_addr;
  assign io_requestor_0_pmp_2_mask = io_dpath_pmp_2_mask;
  assign io_requestor_0_pmp_3_cfg_l = io_dpath_pmp_3_cfg_l;
  assign io_requestor_0_pmp_3_cfg_a = io_dpath_pmp_3_cfg_a;
  assign io_requestor_0_pmp_3_cfg_w = io_dpath_pmp_3_cfg_w;
  assign io_requestor_0_pmp_3_cfg_r = io_dpath_pmp_3_cfg_r;
  assign io_requestor_0_pmp_3_addr = io_dpath_pmp_3_addr;
  assign io_requestor_0_pmp_3_mask = io_dpath_pmp_3_mask;
  assign io_requestor_0_pmp_4_cfg_l = io_dpath_pmp_4_cfg_l;
  assign io_requestor_0_pmp_4_cfg_a = io_dpath_pmp_4_cfg_a;
  assign io_requestor_0_pmp_4_cfg_w = io_dpath_pmp_4_cfg_w;
  assign io_requestor_0_pmp_4_cfg_r = io_dpath_pmp_4_cfg_r;
  assign io_requestor_0_pmp_4_addr = io_dpath_pmp_4_addr;
  assign io_requestor_0_pmp_4_mask = io_dpath_pmp_4_mask;
  assign io_requestor_0_pmp_5_cfg_l = io_dpath_pmp_5_cfg_l;
  assign io_requestor_0_pmp_5_cfg_a = io_dpath_pmp_5_cfg_a;
  assign io_requestor_0_pmp_5_cfg_w = io_dpath_pmp_5_cfg_w;
  assign io_requestor_0_pmp_5_cfg_r = io_dpath_pmp_5_cfg_r;
  assign io_requestor_0_pmp_5_addr = io_dpath_pmp_5_addr;
  assign io_requestor_0_pmp_5_mask = io_dpath_pmp_5_mask;
  assign io_requestor_0_pmp_6_cfg_l = io_dpath_pmp_6_cfg_l;
  assign io_requestor_0_pmp_6_cfg_a = io_dpath_pmp_6_cfg_a;
  assign io_requestor_0_pmp_6_cfg_w = io_dpath_pmp_6_cfg_w;
  assign io_requestor_0_pmp_6_cfg_r = io_dpath_pmp_6_cfg_r;
  assign io_requestor_0_pmp_6_addr = io_dpath_pmp_6_addr;
  assign io_requestor_0_pmp_6_mask = io_dpath_pmp_6_mask;
  assign io_requestor_0_pmp_7_cfg_l = io_dpath_pmp_7_cfg_l;
  assign io_requestor_0_pmp_7_cfg_a = io_dpath_pmp_7_cfg_a;
  assign io_requestor_0_pmp_7_cfg_w = io_dpath_pmp_7_cfg_w;
  assign io_requestor_0_pmp_7_cfg_r = io_dpath_pmp_7_cfg_r;
  assign io_requestor_0_pmp_7_addr = io_dpath_pmp_7_addr;
  assign io_requestor_0_pmp_7_mask = io_dpath_pmp_7_mask;
  assign io_requestor_1_status_debug = io_dpath_status_debug;
  assign io_requestor_1_pmp_0_cfg_l = io_dpath_pmp_0_cfg_l;
  assign io_requestor_1_pmp_0_cfg_a = io_dpath_pmp_0_cfg_a;
  assign io_requestor_1_pmp_0_cfg_x = io_dpath_pmp_0_cfg_x;
  assign io_requestor_1_pmp_0_addr = io_dpath_pmp_0_addr;
  assign io_requestor_1_pmp_0_mask = io_dpath_pmp_0_mask;
  assign io_requestor_1_pmp_1_cfg_l = io_dpath_pmp_1_cfg_l;
  assign io_requestor_1_pmp_1_cfg_a = io_dpath_pmp_1_cfg_a;
  assign io_requestor_1_pmp_1_cfg_x = io_dpath_pmp_1_cfg_x;
  assign io_requestor_1_pmp_1_addr = io_dpath_pmp_1_addr;
  assign io_requestor_1_pmp_1_mask = io_dpath_pmp_1_mask;
  assign io_requestor_1_pmp_2_cfg_l = io_dpath_pmp_2_cfg_l;
  assign io_requestor_1_pmp_2_cfg_a = io_dpath_pmp_2_cfg_a;
  assign io_requestor_1_pmp_2_cfg_x = io_dpath_pmp_2_cfg_x;
  assign io_requestor_1_pmp_2_addr = io_dpath_pmp_2_addr;
  assign io_requestor_1_pmp_2_mask = io_dpath_pmp_2_mask;
  assign io_requestor_1_pmp_3_cfg_l = io_dpath_pmp_3_cfg_l;
  assign io_requestor_1_pmp_3_cfg_a = io_dpath_pmp_3_cfg_a;
  assign io_requestor_1_pmp_3_cfg_x = io_dpath_pmp_3_cfg_x;
  assign io_requestor_1_pmp_3_addr = io_dpath_pmp_3_addr;
  assign io_requestor_1_pmp_3_mask = io_dpath_pmp_3_mask;
  assign io_requestor_1_pmp_4_cfg_l = io_dpath_pmp_4_cfg_l;
  assign io_requestor_1_pmp_4_cfg_a = io_dpath_pmp_4_cfg_a;
  assign io_requestor_1_pmp_4_cfg_x = io_dpath_pmp_4_cfg_x;
  assign io_requestor_1_pmp_4_addr = io_dpath_pmp_4_addr;
  assign io_requestor_1_pmp_4_mask = io_dpath_pmp_4_mask;
  assign io_requestor_1_pmp_5_cfg_l = io_dpath_pmp_5_cfg_l;
  assign io_requestor_1_pmp_5_cfg_a = io_dpath_pmp_5_cfg_a;
  assign io_requestor_1_pmp_5_cfg_x = io_dpath_pmp_5_cfg_x;
  assign io_requestor_1_pmp_5_addr = io_dpath_pmp_5_addr;
  assign io_requestor_1_pmp_5_mask = io_dpath_pmp_5_mask;
  assign io_requestor_1_pmp_6_cfg_l = io_dpath_pmp_6_cfg_l;
  assign io_requestor_1_pmp_6_cfg_a = io_dpath_pmp_6_cfg_a;
  assign io_requestor_1_pmp_6_cfg_x = io_dpath_pmp_6_cfg_x;
  assign io_requestor_1_pmp_6_addr = io_dpath_pmp_6_addr;
  assign io_requestor_1_pmp_6_mask = io_dpath_pmp_6_mask;
  assign io_requestor_1_pmp_7_cfg_l = io_dpath_pmp_7_cfg_l;
  assign io_requestor_1_pmp_7_cfg_a = io_dpath_pmp_7_cfg_a;
  assign io_requestor_1_pmp_7_cfg_x = io_dpath_pmp_7_cfg_x;
  assign io_requestor_1_pmp_7_addr = io_dpath_pmp_7_addr;
  assign io_requestor_1_pmp_7_mask = io_dpath_pmp_7_mask;
  assign io_requestor_1_customCSRs_csrs_0_value = io_dpath_customCSRs_csrs_0_value;
endmodule

