name data_arrays_0_ext depth 512 width 64 ports mrw mask_gran 8 
name tag_array_0_ext depth 64 width 19 ports rw 
name tag_array_0_0_ext depth 64 width 18 ports rw 
name data_arrays_0_0_ext depth 512 width 32 ports rw 
